# Application name (replace with a unique name for your Fly.io app)
app = "univent-platform"

# Primary region for deployment (choose a region close to your database or users, e.g., Frankfurt for eu-central-1)
primary_region = "fra"

# Runtime options
kill_signal = "SIGTERM"
kill_timeout = 120

# Build section for Node.js application
[build]
  # Specify the Dockerfile if you have one, or use buildpacks for Node.js
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]
  [build.args]
    NODE_ENV = "production"

# Environment variables (non-sensitive ones from .env)
[env]
  APP_DOMAIN = "univent.com"
  APP_FRONTEND_HOST = "univent-platform.vercel.app"
  APP_FRONTEND_PORT = "443"
  APP_FRONTEND_PROTOCOL = "https"
  APP_HOST = "univent-platform.fly.io"
  APP_NAME = "Univent"
  APP_NODE_ENV = "production"
  APP_PORT = "8080"
  APP_PROTOCOL = "https"
  APP_SUPPORT_EMAIL = "univent.platform@gmail.com"
  APP_THEME_ID = "1"
  DB_APP_DATABASE = "univent"
  DB_APP_HOST = "gateway01.eu-central-1.prod.aws.tidbcloud.com"
  DB_APP_PORT = "4000"
  DB_APP_USER = "3r594CwdF1zwu1z.root"
  DB_ROOT_HOST = "gateway01.eu-central-1.prod.aws.tidbcloud.com"
  DB_ROOT_PORT = "4000"
  DB_ROOT_USER = "3r594CwdF1zwu1z.root"
  ETHEREAL_HOST = "smtp.ethereal.email"
  ETHEREAL_PORT = "587"
  ETHEREAL_USER = "ricky43@ethereal.email"
  GOOGLE_GMAIL_USER = "univent.platform@gmail.com"
  SHADOW_DB_APP_DATABASE = "univent_shadow"

# HTTP service configuration
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    soft_limit = 50
    hard_limit = 75
  [http_service.http_options]
    idle_timeout = 600

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "30s"
    timeout = "5s"

# Files section for TiDB SSL certificate
[[files]]
  guest_path = "/app/prisma/cert.pem"
  local_path = "./prisma/cert.pem"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
  cpus = 1
  processes = ["app"]

# Processes section
[processes]
  app = "npm run start:prod"
  