// prisma/seeds/themes.ts
import { faker } from '@faker-js/faker';
import { SEED_COUNTS } from './seed-constants';

const themeTypes = [
    'Technology',
    'Business',
    'Entrepreneurship',
    'Marketing',
    'Finance',
    'Investing',
    'Cryptocurrency',
    'Blockchain',
    'Artificial Intelligence',
    'Machine Learning',
    'Data Science',
    'Cybersecurity',
    'Software Development',
    'Web Development',
    'Game Development',
    'Design',
    'Graphic Design',
    'UI/UX Design',
    'Fashion',
    'Art',
    'Photography',
    'Music',
    'Classical Music',
    'Jazz',
    'Rock',
    'Pop',
    'Electronic Music',
    'Literature',
    'Poetry',
    'Writing',
    'History',
    'Science',
    'Astronomy',
    'Biology',
    'Chemistry',
    'Physics',
    'Environment',
    'Sustainability',
    'Climate Change',
    'Health',
    'Mental Health',
    'Wellness',
    'Fitness',
    'Yoga',
    'Meditation',
    'Nutrition',
    'Medicine',
    'Psychology',
    'Education',
    'Career Development',
    'Leadership',
    'Productivity',
    'Personal Development',
    'Self-Improvement',
    'Parenting',
    'Relationships',
    'Travel',
    'Adventure',
    'Culture',
    'Food',
    'Wine Tasting',
    'Cooking',
    'Baking',
    'Sports',
    'Football',
    'Basketball',
    'Tennis',
    'Esports',
    'Gaming',
    'Film',
    'Cinema',
    'Documentary',
    'Theatre',
    'Comedy',
    'Magic',
    'Dance',
    'Ballet',
    'Contemporary Dance',
    'Spirituality',
    'Religion',
    'Philosophy',
    'Politics',
    'Social Justice',
    'Diversity',
    'Inclusion',
    'Networking',
    'Startups',
    'Innovation',
    'Creativity',
    'Engineering',
    'Architecture',
    'Real Estate',
    'Law',
    'Human Rights',
    'Charity',
    'Volunteering',
    'Gardening',
    'DIY (Do It Yourself)',
    'Crafts',
    'Home Improvement',
    'Pets',
    'Animal Welfare',
    'Agriculture',
    'Farming',
    'Blockchain Gaming',
    'NFT (Non-Fungible Tokens)',
    'Metaverse',
    'Virtual Reality',
    'Augmented Reality',
    'Language Learning',
    'Public Speaking',
    'Debate',
    'Astronomy Observation',
    'Stargazing',
    'Wildlife',
    'Marine Life',
    'Space Exploration',
    'Robotics',
    'Quantum Computing',
];

const themeTitles = new Set<string>();

while (themeTitles.size < SEED_COUNTS.THEMES) {
    themeTitles.add(faker.helpers.arrayElement(themeTypes));
}

export const initialThemes = Array.from(themeTitles).map((title, index) => ({
    id: index + 1,
    title,
}));
