export const EVENT_CONSTANTS = {
    MIN_DURATION_MINUTES: 60,
    MIN_PUBLISH_BEFORE_START_HOURS: 24,
} as const;

export const EVENT_TIME_CONSTANTS = {
    MIN_DURATION_MS: EVENT_CONSTANTS.MIN_DURATION_MINUTES * 60 * 1000,
    MIN_PUBLISH_BEFORE_START_MS: EVENT_CONSTANTS.MIN_PUBLISH_BEFORE_START_HOURS * 60 * 60 * 1000,
} as const;
